- packages/tbds-button/lib/button.scss
Example usage markup would be:
```html
<a class="tbds-button" href="#">
<svg class="tbds-button__icon tbds-button__icon--text-to-right">…</svg>
Button Text
</a>
```
---
This is not the exact visual look-and-feel, but the icon buttons would be akin to:
> Add support for icons in buttons

- packages/tbds-app-frame/index.scss
- packages/tbds-app-frame/lib/app-frame.scss
- packages/tbds-app-frame/package.json
A version of this component is already in-use on the [Bourbon website](https://www.bourbon.io/) and [tbot.io](https://tbot.io/). It avoids this:
Here it is in-action (the footer is always pushed to the bottom of the viewport, if there's extra space):
---
Example usage markup:
```html
<body class="app-frame">
<header class="app-frame__header">
</header>
<main class="app-frame__body">
</main>
<footer class="app-frame__footer">
</footer>
</body>
```
> Add app-frame component and package

- packages/tbds-forms/index.scss
- packages/tbds-forms/lib/form-input-button-unit.scss
The `form-input-button-unit` component connects an input and a button together to make one full-width object. It's commonly used for search and newsletter sign up forms.
---
Example usage markup:
```html
<form class="tbds-form-input-button-unit">
<input class="tbds-form-input-button-unit__input" type="search" aria-label="Search">
<button class="tbds-form-input-button-unit__button" type="submit">
Button Text
</button>
</form>
```
> Add form-input-button-unit component

- packages/tbds-button/README.md
We do not currently have a documentation site for tbds. Having a readme in each package directory is a quick and easy way to document that package. GitHub.com and npmjs.com also render these readme's, so users can get a high-level understanding of how to use and work with tbds packages when browsing on those platforms.
> Add README documentation to tbds-button

- .stylelintrc.json
- packages/tbds-utilities/lib/margin.scss
- packages/tbds-utilities/lib/padding.scss
As we do with classes (see [this commit]), this adds a linter to make
sure all of our Sass variables start with `tbds-`, too.
[this commit]: https://github.com/thoughtbot/design-system/commit/e1f54845cfe869642e835fd184cbd8a3501bb1dc
> Stylelint: Check if variables start with `tbds-`

- .stylelintrc.json
Because our design system is meant to be brought in as a library, we
define our Sass variables with a `!default` flag, so that they can be
overwritten if needed.
https://github.com/kristerkari/stylelint-scss/blob/master/src/rules/dollar-variable-default/README.md
> Stylelint: Require `!default` flag for variables

- src/forms/lib/form.scss
- src/settings/lib/color-palette.scss
We based our brand colors off of the press kit, which doesn't have a
defined blue: https://presskit.thoughtbot.com/
There's some thoughtbot.com redesign efforts happening and the team
formalized a blue within the brand color system. You can find this work
in Abstract.
> Update brand blue

- CHANGELOG.md
- src/button/lib/button.scss
- src/elements/lib/typography.scss
- src/settings/index.scss
- src/settings/lib/focus.scss
This adds global variables for styling focus outlines, and uses the
variables to style focus styles on links and buttons.
Visual focus outlines are important for accessibility. They identify
where the active focus is when using devices other than a mouse or
touch input.
_Note: The change in color is from https://github.com/thoughtbot/design-system/pull/82_
> Add global variables for styling focus outlines

- .stylelintrc.json
This would be considered a warning:
```scss
@mixin name-of-mixin { }
```
This would _not_ be considered a warning:
```scss
@mixin tbds-name-of-mixin { }
```
This would be considered a warning:
```scss
@function name-of-function { }
```
This would _not_ be considered a warning:
```scss
@function tbds-name-of-function { }
```
> Stylelint: functions and mixins start with `tbds-`

- CHANGELOG.md
- src/app-frame/lib/app-frame.scss
This modifier class centered content in both axes, so `vertical-middle`
doesn't make the most sense.
> Rename app-frame modifier

- src/settings/lib/breakpoints.scss
A map allows us to easily loop over each of the breakpoints, which will
help with things like generating responsive variants of utility classes.
> Use a map to define breakpoints

- CHANGELOG.md
- src/button/lib/button.scss
Fixes https://github.com/thoughtbot/design-system/issues/95
> Fix button icon alignment

- CHANGELOG.md
- src/settings/index.scss
- src/settings/lib/layout.scss
- src/settings/tools/generate-breakpoint-classes.scss
- src/utilities/README.md
- src/utilities/lib/margin.scss
- src/utilities/lib/padding.scss
- src/utilities/lib/text-align.scss
This allows users to use utility classes to set styles at specific
breakpoints, using a class like `tbds-margin-right-4@medium` where
`medium` is equal to the globally defined `medium` breakpoint.
> Breakpoint-based utility classes

- .stylelintrc.json
- CHANGELOG.md
- package-lock.json
- package.json
- src/app-frame/lib/app-frame.scss
- src/avatar/lib/avatar.scss
- src/button/README.md
- src/button/lib/button.scss
- src/elements/lib/layout.scss
- src/forms/lib/form.scss
- src/forms/lib/input-button-unit.scss
- src/forms/lib/reset.scss
- src/icon/lib/icon.scss
- src/media/README.md
- src/media/lib/media.scss
- src/stack/lib/block-stack.scss
- src/stack/lib/inline-stack.scss
- src/utilities/README.md
- src/utilities/index.scss
- src/utilities/lib/inline-size.scss
- src/utilities/lib/margin.scss
- src/utilities/lib/padding.scss
- src/utilities/lib/text-align.scss
Physical dimensions and directions are described left to right and top
to bottom, while their logical counterparts are described start to end
and inline or block. Logical properties and values are
writing-mode _relative_.
From [the spec](https://drafts.csswg.org/css-logical/):
> Because different writing systems are written in different directions,
> a variety of writing modes exist: left to right, top to bottom; right
> to left, top to bottom; bottom to top, right to left; etc. logical
> concepts like the “start” of a page or line map differently to
> physical concepts like the “top” of a line or “left edge” of a
> paragraph. Some aspects of a layout are actually relative to the
> writing directions, and thus will vary when the page is translated
> to a different system; others are …
> Use logical properties and values

- .stylelintrc.json
Now that we're using more and more CSS Custom Properties over Sass
variables, we should leverage stylelint to check that they are
namespaced with `tbds-`.
The following patterns are considered violations:
```css
html { --color-text-default: #000; }
```
The following patterns are _not_ considered violations:
```css
html { --tbds-color-text-default: #000; }
```
> Enable stylelint custom-property-pattern rule

- CHANGELOG.md
- src/utilities/README.md
- src/utilities/lib/margin.scss
This extends our margin utility classes to also provide the
`auto` value.
The `auto` keyword value for `margin` is commonly used for
inline-centering, or to extend an element's margin to also consume the
extra space in a flex container.
The compiled output of these additions is:
```css
.tbds-margin-block-auto {
margin-block: auto !important;
}
.tbds-margin-block-end-auto {
margin-block-end: auto !important;
}
.tbds-margin-block-start-auto {
margin-block-start: auto !important;
}
.tbds-margin-inline-auto {
margin-inline: auto !important;
}
.tbds-margin-inline-end-auto {
margin-inline-end: auto !important;
}
.tbds-margin-inline-start-auto {
margin-inline-start: auto !important;
}
```
> Add `auto` as a margin utility value

- src/settings/tools/generate-breakpoint-classes.scss
- src/utilities/lib/inline-size.scss
- src/utilities/lib/margin.scss
- src/utilities/lib/padding.scss
- src/utilities/lib/text-align.scss
This refactors the `tbds-generate-breakpoint-classes` mixin to be more
reusable in two ways:
1. The `!important` rule is now opt-in, making it optional.
Before, `!important` rules were always placed on declarations output
by this mixin. This is fine for utilities where we want
`!important`, but when we want to generate breakpoint classes for
non-utilities, we were out of luck.
2. It can now generate more complex selectors.
Before, you passed in a variant (e.g. `start` and `3`) which was
then appended onto the end of the property we were generating
rulesets for (e.g. `text-align-[start]` or `margin-block-[3]`). This
does not account for when you want the variant to be placed in the
_middle_ of a selector, or another place (e.g. `grid--2-columns`).
> Refactor breakpoint class generator mixin

- src/elements/index.scss
- src/elements/lib/layout.scss
- src/elements/lib/media.scss
This PR adds support for images in inverted colors mode. It mirrors work done in https://github.com/thoughtbot/thoughtbot.com/pull/1880.
The inverted colors mode media query is set in `layout.scss`, allowing all images to inherit it.
> Invert images in inverted colors mode

- src/elements/lib/typography.scss
This PR addresses [a conversation in the Bade component about link states](https://github.com/thoughtbot/design-system/pull/131#discussion_r324820332). It updates the `a` element selector to remove the link underline on `hover` and `focus`. This ensures that state change for links does not rely on color alone.
> Link state change

- CHANGELOG.md
- src/badge/lib/badge.scss
- src/settings/lib/color-palette.scss
- src/settings/lib/color.scss
This updates our brand color variables to match the updates recently
made in our [Brand Guidelines][brand-guidelines].
[brand-guidelines]: https://thoughtbot.com/playbook/our-company/brand/colors
> Update brand colors

- CHANGELOG.md
- src/elements/lib/layout.scss
The HTML `hidden` attribute is, in terms of specificity, very weak.
This commit adds `display: none !important;` to the `[hidden]`
attribute selector to ensure that elements using it are actually hidden.
More info: https://css-tricks.com/the-hidden-attribute-is-visibly-weak/
Closes https://github.com/thoughtbot/design-system/issues/138
> Ensure the HTML `hidden` attribute hides content

- .circleci/config.yml
- .gitignore
- CHANGELOG.md
- README.md
- package-lock.json
- package.json
This commit adds npm’s [`prepack` script][npm-scripts] (which
automatically runs before the npm package tarball is created) to compile
tbds’s Sass into CSS.
By distributing compiled CSS in the npm package, we can leverage
[unpkg][unpkg], which is a content delivery network for everything on
npm. unpkg provides URLs like
`https://unpkg.com/@thoughtbot/design-system@0.6.0/dist/tbds.css`,
which would load the tbds CSS at v0.6.0.
Closes https://github.com/thoughtbot/design-system/issues/46
[npm-scripts]: https://docs.npmjs.com/misc/scripts.html
[unpkg]: https://unpkg.com/
---
To do:
> Distribute compiled CSS

- RELEASING.md
- package.json
The npm CLI comes with some commands which script parts of the releasing
process. By using them we reduce friction in releasing and also,
hopefully, prevent small mistakes often causing by having to manually
type portions of the process.
> Leverage npm CLI for releasing

- .stylelintrc.json
- package-lock.json
- package.json
Upgrades all of the JS project dependencies to (hopefully) remove the security issues associated with the orders versions.
**Note** This change replaces `csstools/use-logical` with a fork: `liberty/use-logical-spec` as the former relies on an older (insecure) version of sass, and seems to be unmaintained.
Fixes #196 (#193, #191, #188, #185, #182, #180, #178, #171, #164, #162)
> Upgrade JS dependencies

- CHANGELOG.md
- CONTRIBUTING.md
- RELEASING.md
Updates various documentation files to remove references to the `master` branch, which will no longer be the default branch:
Context: [Migrating thoughtbot Repositories to use Main as default branch](https://thoughtbot.com/blog/making-the-move-master-to-main)
> Update docs to reflect default branch change

- src/settings/lib/layout.scss
- src/settings/tools/strip-unit.scss
While working on [Design Dot](https://github.com/thoughtbot/design-dot), I got the following deprecation warning:
```
Deprecation Warning: Using / for division outside of calc() is
deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div($tbds-base-space-value, 2) or
calc($tbds-base-space-value / 2)
More info and automated migrator: https://sass-lang.com/d/slash-div
╷
5 │   "1": $tbds-base-space-value / 2,
│        ^^^^^^^^^^^^^^^^^^^^^^^^^^
╵
node_modules/@thoughtbot/design-system/src/settings/lib/layout.scss
5:8  @import
node_modules/@thoughtbot/design-system/src/settings/index.scss 5:9
@import
node_modules/@thoughtbot/design-system/src/elements/index.scss 1:9
@import
design-system/src/index.scss 1:9
@import
_includes/assets/sass/style.scss 1:9
root stylesheet
``` …
> Fix calculation warnings

- README.md
This commit corrects the link to the thoughtbot logo in the README.
> Fix the thoughtbot logo link

- bin/setup
- package-lock.json
This commit updates the version of Node to the current LTS. The setup script has also been updated for environments that have `asdf`.
This commit also updates `package.json` with the version that got generated when running the setup script.
Ref:
- https://asdf-vm.com/
- https://nodejs.org/en/download/releases
> Update `.tool-versions` support

- .github/dependabot.yml
This commit moves Dependabot checks to earlier in the week and outside working hours (for most team members).
> Update the Dependabot timing
